app/src/main/res/layout/activity_app_settings.xml
Wrap content layout with ScrollView
=> Bugfix "App Settings not scrollable in landscape mode"

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/ruuvi/station/app/preferences/Preferences.kt, app/src/main/java/com/ruuvi/station/bluetooth/DefaultOnTagFoundListener.kt, app/src/main/java/com/ruuvi/station/database/tables/TagSensorReading.java, app/src/main/java/com/ruuvi/station/gateway/GatewaySender.kt, app/src/main/java/com/ruuvi/station/graph/GraphView.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsGraphFragment.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsGraphViewModel.kt, app/src/main/java/com/ruuvi/station/tagdetails/domain/TagDetailsInteractor.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsViewModel.kt, app/src/main/java/com/ruuvi/station/util/Constants.kt, app/src/main/java/com/ruuvi/station/util/Starter.kt, app/src/main/res/layout/fragment_app_settings_graph.xml, app/src/main/res/values/strings.xml
[CHANGED] notification changes
[CHANGED] tag card opening
=> [CHANGED] graph refactoring part 4

app/src/main/res/layout/fragment_app_settings_graph.xml
=> ISSUE ANDROID-137

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/java/com/ruuvi/station/util/CsvExporter.kt
[FIXED] Temperature, pressure and humidity export in selected units
=> ISSUE ANDROID-169  Unify iOS, Android CSV export units

app/src/main/java/com/ruuvi/station/dashboard/di/DashboardActivityInjectionModule.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivity.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivityViewModel.kt
=> ISSUE ANDROID-172  1.2.8 Bell on dashboard has gone quite bonkers

app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsViewModel.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagViewModel.kt
[FIXED] Tag card "updated" refresh every second
[skip ci]
=> ISSUE ANDROID-174  1.2.9 Updated counter is frozen after update

app/src/main/java/com/ruuvi/station/bluetooth/DefaultOnTagFoundListener.kt, app/src/main/java/com/ruuvi/station/bluetooth/di/BluetoothScannerInjectionModule.kt, app/src/main/java/com/ruuvi/station/bluetooth/domain/LocationInteractor.kt
[FIXED] Optimized getting location for gateway, saving new data points in separate thread
[skip ci]
=> ISSUE ANDROID-119 Show all datapoints makes phone slow down drastically

app/src/main/java/com/ruuvi/station/addtag/ui/AddTagActivity.kt, app/src/main/java/com/ruuvi/station/addtag/ui/AddTagActivityViewModel.kt, app/src/main/java/com/ruuvi/station/app/RuuviScannerApplication.kt, app/src/main/java/com/ruuvi/station/bluetooth/DefaultOnTagFoundListener.kt, app/src/main/java/com/ruuvi/station/bluetooth/domain/LocationInteractor.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivity.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivityViewModel.kt, app/src/main/java/com/ruuvi/station/tag/domain/TagInteractor.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsViewModel.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagViewModel.kt
[FIXED] all timers moved from viewModels to activity or fragments
[skip ci]
=> ISSUE ANDROID-182  Unwanted background activity

app/src/main/java/com/ruuvi/station/units/domain/UnitsConverter.kt
=> ISSUE ANDROID-190 Invalid value showed if humidity is 100%

app/build.gradle
[FIXED] using latest BT lib
[skip ci]
=> ISSUE ANDROID-131 Read history logs via GATT

app/src/main/java/com/ruuvi/station/gateway/GatewaySender.kt
ISSUE Gateway test sends event datetime in incorrect format #75
ISSUE DateTime timezone is missing a : #92
[FIXED] timezone for gateway data send
=> ISSUE Gateway test sends event datetime in incorrect format #75

app/src/main/java/com/ruuvi/station/util/CsvExporter.kt
[FIXED] filename now is same as in iOS
=> ISSUE File name for export could be better (enhancement) #88

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt
[FIXED] Open dialog with correct context
=> ISSUE #190 Video tutorials link lead to app crash (in calibrate tag)

app/build.gradle, app/src/main/java/com/ruuvi/station/database/tables/TagSensorReading.java
=> ISSUE #195 1.4.2. Sync gets stuck on saving fw 3.29.1

app/src/main/java/com/ruuvi/station/gateway/GatewaySender.kt
[FIXED] date format for GatewaySender
=> ISSUE #200 Crash on app start for Android 6 users

app/build.gradle, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsBackgroundScanFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/util/PermissionsHelper.kt, app/src/main/res/values/strings.xml
[CHANGED] Messages for user
[FIXED] Behavior for updated version
=> ISSUE #199 Background work for Android 11

app/src/main/res/values/strings.xml
[FIXED] small changes to strings.xml
=> ISSUE #184 Language unification Android

app/src/main/AndroidManifest.xml, app/src/main/res/values/strings.xml
=> ISSUE #213 Remove mentions of "tags" in app

app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsViewModel.kt
[FIXED] correct icon for graph button
=> ISSUE #207 1.4.9 Graphs icon is reversed

app/src/main/java/com/ruuvi/station/graph/GraphView.kt
FIXED some cosmetic changes to charts
=> ISSUE #241 Improve timeline for graphs (dates and time)

app/src/main/java/com/ruuvi/station/alarm/domain/AlarmCheckInteractor.kt, app/src/main/java/com/ruuvi/station/database/LocalDatabase.java, app/src/main/java/com/ruuvi/station/database/tables/Alarm.java, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/layout/view_alarm.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
[ADDED] custom alert description
[skip ci]
=> ISSUE #185 Custom alert descriptions

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/drawable/ic_muted_notifications.xml, app/src/main/res/layout/view_alarm.xml
FIXED way to show muted alerts
[skip ci]
=> ISSUE #159 Show in settings if alert is currently muted

app/src/main/java/com/ruuvi/station/units/domain/PressureConverter.kt, app/src/main/java/com/ruuvi/station/units/domain/TemperatureConverter.kt, app/src/main/java/com/ruuvi/station/units/domain/UnitsConverter.kt
=> ISSUE #259 Temperature rounding issue in csv export

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/layout/activity_tag_settings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> ISSUE #186 Android Tag Settings - More info

app/build.gradle, app/src/main/java/com/ruuvi/station/util/Foreground.kt
ISSUE #277 App gateway feature occasionally sends data too often
[skip ci]
=> ISSUE #237 More datapoints than was requested by settings

app/src/main/java/com/ruuvi/station/app/preferences/GlobalSettings.kt, app/src/main/java/com/ruuvi/station/app/preferences/Preferences.kt, app/src/main/java/com/ruuvi/station/app/preferences/PreferencesRepository.kt, app/src/main/java/com/ruuvi/station/bluetooth/DefaultOnTagFoundListener.kt, app/src/main/java/com/ruuvi/station/database/TagRepository.kt, app/src/main/java/com/ruuvi/station/database/tables/TagSensorReading.java, app/src/main/java/com/ruuvi/station/firebase/domain/FirebasePropertiesSaver.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt, app/src/main/java/com/ruuvi/station/settings/domain/AppSettingsInteractor.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsGraphFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagViewModel.kt, app/src/main/java/com/ruuvi/station/util/CsvExporter.kt, app/src/main/res/layout/fragment_app_settings_graph.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
ISSUE #284 CSV export contains only time span shown in graph
=> ISSUE #275 Unify stored data history length with iOS

app/src/main/res/layout/view_graphs.xml, app/src/main/res/values/styles.xml
[FIXED] style applied to buttons
=> ISSUE #291 Descriptions don't fit in the buttons

app/build.gradle, app/src/main/java/com/ruuvi/station/database/LocalDatabase.java, app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt
[FIXED] sensor order
[skip ci]
=> ISSUE #303 1.5.4 Add network sensors after the rightmost card

app/src/main/java/com/ruuvi/station/util/CsvExporter.kt
=> ISSUE #281 CSV export: in file name hh is in 12 hour

app/src/main/java/com/ruuvi/station/network/ui/EmailEnterFragment.kt, app/src/main/java/com/ruuvi/station/network/ui/EmailEnterViewModel.kt, app/src/main/java/com/ruuvi/station/network/ui/EnterCodeFragment.kt, app/src/main/java/com/ruuvi/station/network/ui/EnterCodeViewModel.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/res/layout/fragment_email_enter.xml, app/src/main/res/layout/fragment_enter_code.xml, app/src/main/res/values/styles.xml
[FIXED] request code only once
ISSUE #328 Changes to sign in process
[REMOVED] Skip buttons and 'sign in benefits' dialog
=> ISSUE #321 Ruuvi Network Login Code Request

app/src/main/java/com/ruuvi/station/database/domain/SensorHistoryRepository.kt
=> ISSUE #309 1.5.5 app is freezing in charts view

app/src/main/java/com/ruuvi/station/calibration/ui/CalibrateHumidityFragment.kt, app/src/main/java/com/ruuvi/station/calibration/ui/CalibratePressureFragment.kt, app/src/main/java/com/ruuvi/station/calibration/ui/CalibrateTemperatureFragment.kt, app/src/main/java/com/ruuvi/station/calibration/ui/CalibrationFragment.kt
[CHANGED] calibration instructions
=> ISSUE #274 Sensor offset calibration

app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivity.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkTokenRepository.kt
Removed Network benefits dialog for dashboard
=> [FIXED] Clearing last network sync on sign out

app/src/main/java/com/ruuvi/station/bluetooth/domain/BluetoothGattInteractor.kt, app/src/main/java/com/ruuvi/station/tagdetails/di/TagDetailsInjectionModule.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagViewModel.kt
[FIXED] constant repeat of disconnected dialog
=> ISSUE #367 Crash on GATT sync (from crashlytics)

app/src/main/java/com/ruuvi/station/alarm/domain/AlarmElement.kt, app/src/main/java/com/ruuvi/station/alarm/domain/AlarmType.kt, app/src/main/java/com/ruuvi/station/calibration/domain/CalibrationInteractor.kt, app/src/main/java/com/ruuvi/station/database/domain/AlarmRepository.kt, app/src/main/java/com/ruuvi/station/database/model/NetworkRequestType.kt, app/src/main/java/com/ruuvi/station/network/data/request/GetAlertsRequest.kt, app/src/main/java/com/ruuvi/station/network/data/request/SetAlertRequest.kt, app/src/main/java/com/ruuvi/station/network/data/request/UpdateSensorRequest.kt, app/src/main/java/com/ruuvi/station/network/data/requestWrappers/RequestWrapper.kt, app/src/main/java/com/ruuvi/station/network/data/requestWrappers/UploadImageRequestWrapper.kt, app/src/main/java/com/ruuvi/station/network/data/response/GetAlertsResponse.kt, app/src/main/java/com/ruuvi/station/network/data/response/GetSensorsResponse.kt, app/src/main/java/com/ruuvi/station/network/data/response/SetAlarmResponse.kt, app/src/main/java/com/ruuvi/station/network/di/NetworkInjectionModule.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkAlertsSyncInteractor.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkRequestExecutor.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkApi.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkInteractor.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkRepository.kt, app/src/main/java/com/ruuvi/station/network/ui/ShareSensorViewModel.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsViewModel.kt
[ADDED] Support for network alerts
=> ISSUE #377 Implement Network Alerts

app/build.gradle
[FIXED] resetting state of GattConnection should help to prevent disconnected message on successful sync
=> ISSUE #413 GATT sync occasionally gives a Disconnected pop-up

app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/res/layout/activity_tag_details.xml
=> ISSUE #419 Unification: no sensors screen

app/src/main/res/layout/activity_share_sensor.xml
=> ISSUE #434 Sensor sharing keyboard layout is not correct

app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt
=> ISSUE #451 No enough data downloaded from the cloud when synced

app/src/main/java/com/ruuvi/station/alarm/domain/AlarmType.kt, app/src/main/java/com/ruuvi/station/alarm/ui/AlarmEditView.kt, app/src/main/java/com/ruuvi/station/database/tables/Alarm.kt, app/src/main/java/com/ruuvi/station/network/data/request/SetAlertRequest.kt, app/src/main/java/com/ruuvi/station/network/di/NetworkInjectionModule.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkInteractor.kt, app/src/main/java/com/ruuvi/station/network/ui/ClaimSensorViewModel.kt
[FIXED] saving everything on successful claim
=> ISSUE #449 Save offsets, alarms and background image on sensor claim

app/src/main/java/com/ruuvi/station/network/ui/ShareSensorActivity.kt
=> ISSUE #460 Fi language doesn't fit email in remove sharing popup

app/src/main/java/com/ruuvi/station/database/domain/TagRepository.kt
[CHANGED] collate to LOCALIZED
=> ISSUE #476 Sensors with scandic letters aren't organized correctly

app/src/main/java/com/ruuvi/station/calibration/di/CalibrationInjectionModule.kt, app/src/main/java/com/ruuvi/station/calibration/domain/CalibrationInteractor.kt, app/src/main/java/com/ruuvi/station/database/domain/SensorHistoryRepository.kt, app/src/main/java/com/ruuvi/station/database/tables/SensorSettings.kt, app/src/main/java/com/ruuvi/station/network/di/NetworkInjectionModule.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt
[ADDED] auto calibration for history
=> ISSUE #415 Apply offsets to existing history data

app/build.gradle, app/src/main/java/com/ruuvi/station/bluetooth/di/BluetoothScannerInjectionModule.kt, app/src/main/java/com/ruuvi/station/bluetooth/domain/BluetoothGattInteractor.kt, app/src/main/java/com/ruuvi/station/firebase/domain/FirebaseInteractor.kt
=> ISSUE #418 Add Firebase analytics

app/build.gradle
[CHANGED] com.koushikdutta.ion:ion version changed to 3.1.0
=> ISSUE #525 Data Forwarding is crashing app on latest version

app/src/main/res/navigation/sign_in_navigation.xml
=> ISSUE #428 Prepare/check app for upcoming Android 12

app/src/main/java/com/ruuvi/station/bluetooth/domain/PermissionsInteractor.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/layout/activity_tag_settings.xml
[CHANGED] also fixed issue for Android 12
=> ISSUE #536 Open alarm settings when user click on bell icon

app/src/main/java/com/ruuvi/station/settings/di/SettingsInjectionModule.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsActivity.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsViewModel.kt, app/src/main/java/com/ruuvi/station/startup/ui/StartupActivity.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
[CHANGED] automatically restart app on dashboard setting change
=> ISSUE #421 Fix Dashboard changing without need to restart app

app/src/main/AndroidManifest.xml
[CHANGED] SignInActivity exported changed to TRUE
=> ISSUE #540 Gmail crash when trying to open Log in link (Android 12)

app/src/main/java/com/ruuvi/station/dfu/di/DfuInjectionModule.kt, app/src/main/java/com/ruuvi/station/dfu/ui/DfuUpdateActivity.kt, app/src/main/java/com/ruuvi/station/dfu/ui/DfuUpdateViewModel.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
[ADDED] warning before updating sensor FW
=> ISSUE #538 Warn user before FW update if his battery level is low

app/build.gradle
=> ISSUE #557 Bluetooth crash specific for Android 12

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/layout/activity_share_sensor.xml, app/src/main/res/layout/activity_tag_settings.xml, app/src/main/res/values/styles.xml
[CHANGED] tag settings layout fixed. UI elements renaming according with code-style
=> ISSUE #552 Extra large font issue

app/src/main/java/com/ruuvi/station/bluetooth/DefaultOnTagFoundListener.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> ISSUE #567 Saving history issue

app/src/main/java/com/ruuvi/station/firebase/domain/FirebaseInteractor.kt
[ADDED] number of logged_in users
=> ISSUE #583

app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkInteractor.kt, app/src/main/java/com/ruuvi/station/widgets/domain/WidgetInteractor.kt
[CHANGED] request mode changed to MIXED
=> ISSUE #549 Widgets

app/build.gradle, app/src/main/java/com/ruuvi/station/network/domain/NetworkApplicationSettings.kt, app/src/main/java/com/ruuvi/station/settings/domain/AppSettingsInteractor.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsGraphViewModel.kt, app/src/main/java/com/ruuvi/station/settings/ui/AppSettingsHumidityViewModel.kt
[CHANGED] added logging and little clean up
=> ISSUE #593 Settings get overwritten from cloud

app/src/main/AndroidManifest.xml, app/src/main/java/com/ruuvi/station/graph/GraphView.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagFragment.kt, app/src/main/res/layout-land/view_graphs.xml
[ADDED] new behaviour for horizontal layout
=> ISSUE #270 1.4.22 Chart units in landscape still overlapping

app/src/main/java/com/ruuvi/station/tagsettings/di/TagSettingsInjectionModule.kt, app/src/main/java/com/ruuvi/station/tagsettings/domain/TagSettingsInteractor.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsViewModel.kt
[CHANGED] automatic update added, hiding empty value
=> ISSUE #508 Display firmware version of tag in settings

app/src/main/java/com/ruuvi/station/tagsettings/domain/CsvExporter.kt, app/src/main/java/com/ruuvi/station/units/domain/UnitsConverter.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
[ADDED] temperature rounding, tx power added for data format 5
=> ISSUE #579 Export CSV dissimilarities on iOS and Android

app/src/main/java/com/ruuvi/station/firebase/domain/FirebaseInteractor.kt
=> ISSUE #606 Add firebase metric to determine if user got sensors with df3

app/src/main/java/com/ruuvi/station/database/tables/TagSensorReading.kt
[FIXED] cloud sync for pressure and humidity
=> ISSUE #575 Hide charts for missing sensors (pressure for example)

app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsViewModel.kt
[CHANGED] visibility of firmware section when sensor was shared to current user
=> ISSUE #631 Hide Firmware section for shared sensor in sensor settings

app/src/main/java/com/ruuvi/station/network/domain/NetworkDataSyncInteractor.kt
[FIXED] cloud sync to avoid duplicates
=> ISSUE #638 Remove duplicate samples from the exported CSV

app/src/main/AndroidManifest.xml, app/src/main/java/com/ruuvi/station/network/ui/EmailEnterFragment.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsViewModel.kt, app/src/main/java/com/ruuvi/station/welcome/ui/WelcomeActivity.kt, app/src/main/res/layout/activity_welcome.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
[ADDED] new page to ask user to sign in
=> ISSUE #644 Onboarding: Ruuvi Cloud

app/src/main/res/layout/fragment_email_enter.xml, app/src/main/res/layout/fragment_enter_code.xml, app/src/main/res/values/styles.xml
[FIXED] Fonts for sign in screen
=> ISSUE Onboarding: Ruuvi Cloud #644

app/src/main/java/com/ruuvi/station/database/tables/RuuviTagEntity.kt, app/src/main/java/com/ruuvi/station/dfu/ui/DfuUpdateViewModel.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsViewModel.kt, app/src/main/res/layout/activity_tag_settings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
[ADDED] Battery warning to sensor settings
=> ISSUE #335 Show a battery capacity indicator

app/src/main/java/com/ruuvi/station/bluetooth/domain/PermissionsInteractor.kt, app/src/main/java/com/ruuvi/station/calibration/ui/CalibrationFragment.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivity.kt, app/src/main/java/com/ruuvi/station/dataforwarding/domain/LocationPermissionsInteractor.kt, app/src/main/java/com/ruuvi/station/network/ui/ShareSensorActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagFragment.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/TagSettingsActivity.kt, app/src/main/res/drawable/rounded_dialog.xml, app/src/main/res/layout/activity_tag_settings.xml, app/src/main/res/layout/bottom_sheet_select_image_source.xml, app/src/main/res/layout/content_add_tag.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values-notnight/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
[FIXED] Dialog style and other small issues
=> ISSUE #366 Dark mode (theme)

app/src/main/res/drawable/button_rounded_corners.xml, app/src/main/res/layout/content_about.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values-notnight/themes.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml
=> ISSUE #695 UI fix: Buttons

app/src/main/java/com/ruuvi/station/app/ui/theme/Typography.kt, app/src/main/java/com/ruuvi/station/dfu/ui/DfuUpdateActivity.kt, app/src/main/java/com/ruuvi/station/widgets/ui/WidgetsCommonElements.kt, app/src/main/res/layout/activity_about.xml, app/src/main/res/layout/activity_add_tag.xml, app/src/main/res/layout/activity_app_settings.xml, app/src/main/res/layout/activity_calibration.xml, app/src/main/res/layout/activity_claim_sensor.xml, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/activity_share_sensor.xml, app/src/main/res/layout/activity_tag_details.xml, app/src/main/res/layout/activity_tag_settings.xml, app/src/main/res/layout/dialog_sensor_name_edit.xml, app/src/main/res/layout/fragment_app_settings_list.xml, app/src/main/res/values/styles.xml
Fixed style for toolbar and input
=> ISSUE #696 UI fix: Fonts

app/src/main/java/com/ruuvi/station/addtag/ui/AddTagActivity.kt, app/src/main/java/com/ruuvi/station/dashboard/ui/DashboardActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/TagDetailsActivity.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
ISSUE #747 Localise "Buy sensors" and "Buy Gateway" links
=> ISSUE #746 Add "What to measure with Ruuvi?" link on the menu

app/src/main/java/com/ruuvi/station/graph/CustomXAxisRenderer.kt
[FIXED] considering daylight saving now
=> ISSUE #778 Chart select baseline points incorrectly 01:00 instead 00:00

app/src/main/java/com/ruuvi/station/image/ImageInteractor.kt
[CHANGED] cropping disabled. resizing to 1080p width from now on.
=> ISSUE #781 Investigate bg image croping #781

app/src/main/java/com/ruuvi/station/app/ui/theme/Color.kt, app/src/main/java/com/ruuvi/station/tagsettings/ui/SensorSettingsElements.kt
[CHANGED] Titles background color and divider color
=> ISSUE #711 Changes to alert settings

app/src/main/java/com/ruuvi/station/graph/GraphView.kt
[CHANGED] Bottom chart padding to fit captions with big font
=> ISSUE #787 Graph view changes (font, temperature text alignment..)

app/src/main/java/com/ruuvi/station/database/domain/AlarmRepository.kt
[FIXED] Strange values for movement alerts
=> ISSUE #786 Redesign sensor settings

app/src/main/java/com/ruuvi/station/alarm/domain/AlarmsInteractor.kt, app/src/main/java/com/ruuvi/station/alarm/ui/AlarmItemsViewModel.kt, app/src/main/java/com/ruuvi/station/alarm/ui/AlarmsGroup.kt, app/src/main/java/com/ruuvi/station/database/domain/AlarmRepository.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkAlertsSyncInteractor.kt, app/src/main/res/values/strings.xml
ISSUE #818 Alerts: Snoozing alert from notifications showing in sensor settings
=> ISSUE #822 Remove Alert text from each alerts setting

app/src/main/java/com/ruuvi/station/alarm/ui/AlarmItemsViewModel.kt, app/src/main/java/com/ruuvi/station/alarm/ui/AlarmsGroup.kt, app/src/main/java/com/ruuvi/station/network/domain/NetworkAlertsSyncInteractor.kt
[FIXED] muted and disable buttons
=> ISSUE #850 Check notifications for alerts with decimal limits

app/src/main/java/com/ruuvi/station/network/data/response/GetSubscriptionResponse.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkApi.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkInteractor.kt, app/src/main/java/com/ruuvi/station/network/domain/RuuviNetworkRepository.kt, app/src/main/java/com/ruuvi/station/network/ui/MyAccountActivity.kt, app/src/main/java/com/ruuvi/station/network/ui/MyAccountViewModel.kt
=> ISSUE #854 New dashboard layout

app/src/main/java/com/ruuvi/station/graph/GraphView.kt
=> ISSUE #898 Small chart fixes

app/src/main/java/com/ruuvi/station/firebase/domain/PushAlertInteractor.kt
Support for locally muting push alerts
=> ISSUE #902 Push notifications preparations

scripts/ci/update_l10n.sh
Implements sh script to generate localizations from station.localization repo. 
Usage: 
```shell
./scripts/ci/update_l10n.sh
```
=> Generate localizations script

app/build.gradle, app/src/main/java/com/ruuvi/station/app/permissions/PermissionsInteractor.kt, app/src/main/java/com/ruuvi/station/dfu/ui/DfuUpdateViewModel.kt
[ADDED] check to not allow firmware downgrade
=> ISSUE #1191 Adding new dataformat support

app/src/main/java/com/ruuvi/station/app/preferences/Preferences.kt, app/src/main/java/com/ruuvi/station/app/preferences/PreferencesRepository.kt, app/src/main/java/com/ruuvi/station/graph/ChartsView.kt, app/src/main/java/com/ruuvi/station/settings/ui/DeveloperSettings.kt, app/src/main/java/com/ruuvi/station/settings/ui/DeveloperSettingsViewModel.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/SensorCardActivity.kt, app/src/main/java/com/ruuvi/station/tagdetails/ui/SensorCardViewModel.kt
New UI hidden under feature flag
=> ISSUE #1225 Redesign text layouts for history view
